app:
  name: "bluebell"
  mode: "dev"
  port: 9090
  startTime: "2021-08-23"
  machineId: 1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"

# redis host 记得改成阿里云服务器
redis:
  host: "localhost"
  port: 6379
  db: 0
  auth: "lmx15521144359"

